version: "3"

services:
    mongo:
        image: mongo
        container_name: mongodb
        volumes:
            # Montamos un volumen para MongoDB para no perder los datos de la bd
            - $HOME/mongo:/data/db
        command: --serviceExecutor adaptive

    tadcinema:
        image: maven
        container_name: tadcinema
        restart: always
        volumes:
            - .:/TADCinema
        working_dir: /TADCinema
        expose:
            - "8080"
        ports:
            - "8080:8080"
        links:
            - mongo
        # Comando para la ejecución de la aplicación
        command: mvn jetty:run